components:
  securitySchemes:
    Api-Key-Cookie-Auth:
      in: cookie
      name: Auth
      type: apiKey
    Api-Key-Header-Auth:
      in: header
      name: Auth
      type: apiKey
    Api-Key-Query-Auth:
      in: query
      name: Auth
      type: apiKey
    HTTP-Basic-Auth:
      scheme: basic
      type: http
    HTTP-Bearer-Auth:
      scheme: bearer
      type: http
    HTTP-Digest-Auth:
      scheme: digest
      type: http
    OIDC-Auth:
      openIdConnectUrl: https://domain.tld/oidc
      type: openIdConnect
    Oauth2-Auth:
      flows:
        authorizationCode:
          authorizationUrl: https://domain.tld/auth
          refreshUrl: https://domain.tld/token
          scopes:
            scope-1: this is scope 1
            scope-2: ""
            scope-3: ""
          tokenUrl: https://domain.tld/token
      type: oauth2
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test1:
    get:
      responses:
        "204":
          description: Ok
      security:
      - HTTP-Basic-Auth: []
      x-codeSamples:
      - label: curl
        lang: curl
        source: |-
          USERNAME="user"
          PASSWORD="******"

          curl https://domain.tld/test1 -X GET -u ${USERNAME}:${PASSWORD}
      - label: php
        lang: php
        source: |2-

          $username = "username";
          $password = "********";
          $url = "https://domain.tld/test1";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($ch, CURLOPT_USERPWD, $username . \":\" . $password);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
  /test2:
    get:
      responses:
        "204":
          description: Ok
      security:
      - HTTP-Bearer-Auth: []
      x-codeSamples:
      - label: curl
        lang: curl
        source: |-
          TOKEN="my secure token"

          curl https://domain.tld/test2 -X GET -H "Authorization: Bearer ${TOKEN}"
      - label: php
        lang: php
        source: |2-

          $token = "my secret token";
          $url = "https://domain.tld/test2";
          $headers = array(
              "Authorization: " . \"Bearer \" . $token,
          );

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
  /test3:
    get:
      responses:
        "204":
          description: Ok
      security:
      - HTTP-Digest-Auth: []
      x-codeSamples:
      - label: curl
        lang: curl
        source: |2-

          curl https://domain.tld/test3 -X GET
      - label: php
        lang: php
        source: |-
          $url = "https://domain.tld/test3";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
  /test4:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Api-Key-Header-Auth: []
      x-codeSamples:
      - label: curl
        lang: curl
        source: |-
          TOKEN="my secure token"

          curl https://domain.tld/test4 -X GET -H "Auth: ${TOKEN}"
      - label: php
        lang: php
        source: |2-

          $token = "my secret token";
          $url = "https://domain.tld/test4";
          $headers = array(
              "Auth: " . $token,
          );

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
  /test5:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Api-Key-Query-Auth: []
      x-codeSamples:
      - label: curl
        lang: curl
        source: |-
          TOKEN="my secure token"

          curl https://domain.tld/test5?Auth=${TOKEN}& -X GET
      - label: php
        lang: php
        source: |2-

          $token = "my secret token";
          $url = "https://domain.tld/test5?Auth=" . $token . "&";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
  /test6:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Api-Key-Cookie-Auth: []
      x-codeSamples:
      - label: curl
        lang: curl
        source: |-
          TOKEN="my secure token"

          curl https://domain.tld/test6 -X GET -b "Auth=${TOKEN}"
      - label: php
        lang: php
        source: |2-

          $token = "my secret token";
          $url = "https://domain.tld/test6";
          $cookies = ""Auth=" . $token . ";";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_COOKIE, $cookies);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
  /test7:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Oauth2-Auth:
        - scope-1
        - scope-3
      x-codeSamples:
      - label: curl
        lang: curl
        source: |-
          TOKEN="my secure token"

          curl https://domain.tld/test7 -X GET -H "Authorization: Bearer ${TOKEN}"
      - label: php
        lang: php
        source: |2-

          $token = "my secret token";
          $url = "https://domain.tld/test7";
          $headers = array(
              "Authorization: " . \"Bearer \" . $token,
          );

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
  /test8:
    get:
      responses:
        "204":
          description: Ok
      security:
      - OIDC-Auth: []
      x-codeSamples:
      - label: curl
        lang: curl
        source: |-
          TOKEN="my secure token"

          curl https://domain.tld/test8 -X GET -H "Authorization: Bearer ${TOKEN}"
      - label: php
        lang: php
        source: |2-

          $token = "my secret token";
          $url = "https://domain.tld/test8";
          $headers = array(
              "Authorization: " . \"Bearer \" . $token,
          );

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
