components:
  securitySchemes:
    Api-Key-Cookie-Auth:
      in: cookie
      name: Auth
      type: apiKey
    Api-Key-Header-Auth:
      in: header
      name: Auth
      type: apiKey
    Api-Key-Query-Auth:
      in: query
      name: Auth
      type: apiKey
    HTTP-Basic-Auth:
      scheme: basic
      type: http
    HTTP-Bearer-Auth:
      scheme: bearer
      type: http
    HTTP-Digest-Auth:
      scheme: digest
      type: http
    OIDC-Auth:
      openIdConnectUrl: https://domain.tld/oidc
      type: openIdConnect
    Oauth2-Auth:
      flows:
        authorizationCode:
          authorizationUrl: https://domain.tld/auth
          refreshUrl: https://domain.tld/token
          scopes:
            scope-1: this is scope 1
            scope-2: ""
            scope-3: ""
          tokenUrl: https://domain.tld/token
      type: oauth2
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test1:
    get:
      responses:
        "204":
          description: Ok
      security:
      - HTTP-Basic-Auth: []
      x-codeSamples:
      - lang: curl
        source: |-
          USERNAME="user"
          PASSWORD="******"
          
          curl https://domain.tld/test1 -X GET -u ${USERNAME}:${PASSWORD}
        label: bash/curl
      - lang: php
        source: "\n$username = \"username\";\n$password = \"********\";\n$url = \"https://domain.tld/test1\";\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST, \"GET\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($ch, CURLOPT_USERPWD, $username . \\\":\\\" . $password);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
        label: PHP
      - lang: js
        source: |-
          
          var username = "username";
          var password = "********";
          var url = "https://domain.tld/test1";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          request.setRequestHeader("Authorization", "Basic " + btoa(username + ":" + password));
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
  /test2:
    get:
      responses:
        "204":
          description: Ok
      security:
      - HTTP-Bearer-Auth: []
      x-codeSamples:
      - lang: curl
        source: "TOKEN=\"my secure token\"\ncurl https://domain.tld/test2 -X GET -H \"Authorization: Bearer ${TOKEN}\""
        label: bash/curl
      - lang: php
        source: "$token = \"my secret token\";\n$url = \"https://domain.tld/test2\";\n$headers = array(\n    \"Authorization: \" . \"Bearer \" . $token,\n);\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST, \"GET\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_HTTPHEADER, $headers);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
        label: PHP
      - lang: js
        source: |-
          var token = "my secret token";
          var url = "https://domain.tld/test2";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          request.setRequestHeader("Authorization", "Bearer " + token);
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
  /test3:
    get:
      responses:
        "204":
          description: Ok
      security:
      - HTTP-Digest-Auth: []
      x-codeSamples:
      - lang: curl
        source: curl https://domain.tld/test3 -X GET
        label: bash/curl
      - lang: php
        source: |-
          $url = "https://domain.tld/test3";
          
          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
        label: PHP
      - lang: js
        source: |-
          
          var url = "https://domain.tld/test3";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
  /test4:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Api-Key-Header-Auth: []
      x-codeSamples:
      - lang: curl
        source: "TOKEN=\"my secure token\"\ncurl https://domain.tld/test4 -X GET -H \"Auth: ${TOKEN}\""
        label: bash/curl
      - lang: php
        source: "$token = \"my secret token\";\n$url = \"https://domain.tld/test4\";\n$headers = array(\n    \"Auth: \" . $token,\n);\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST, \"GET\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_HTTPHEADER, $headers);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
        label: PHP
      - lang: js
        source: |-
          var token = "my secret token";
          var url = "https://domain.tld/test4";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          request.setRequestHeader("Auth", token);
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
  /test5:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Api-Key-Query-Auth: []
      x-codeSamples:
      - lang: curl
        source: |-
          TOKEN="my secure token"
          curl https://domain.tld/test5?Auth=${TOKEN}& -X GET
        label: bash/curl
      - lang: php
        source: |-
          $token = "my secret token";
          $url = "https://domain.tld/test5?Auth=" . $token . "&";
          
          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
        label: PHP
      - lang: js
        source: |-
          var token = "my secret token";
          var url = "https://domain.tld/test5?Auth=" + token + "&";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
  /test6:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Api-Key-Cookie-Auth: []
      x-codeSamples:
      - lang: curl
        source: |-
          TOKEN="my secure token"
          curl https://domain.tld/test6 -X GET -b "Auth=${TOKEN}"
        label: bash/curl
      - lang: php
        source: |-
          $token = "my secret token";
          $url = "https://domain.tld/test6";
          $cookies = "Auth=" . $token . ";";
          
          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "GET");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_COOKIE, $cookies);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
        label: PHP
      - lang: js
        source: |-
          var token = "my secret token";
          var url = "https://domain.tld/test6";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
  /test7:
    get:
      responses:
        "204":
          description: Ok
      security:
      - Oauth2-Auth:
        - scope-1
        - scope-3
      x-codeSamples:
      - lang: curl
        source: "TOKEN=\"my secure token\"\ncurl https://domain.tld/test7 -X GET -H \"Authorization: Bearer ${TOKEN}\""
        label: bash/curl
      - lang: php
        source: "$token = \"my secret token\";\n$url = \"https://domain.tld/test7\";\n$headers = array(\n    \"Authorization: \" . \"Bearer \" . $token,\n);\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST, \"GET\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_HTTPHEADER, $headers);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
        label: PHP
      - lang: js
        source: |-
          var token = "my secret token";
          var url = "https://domain.tld/test7";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          request.setRequestHeader("Authorization", "Bearer " + token);
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
  /test8:
    get:
      responses:
        "204":
          description: Ok
      security:
      - OIDC-Auth: []
      x-codeSamples:
      - lang: curl
        source: "TOKEN=\"my secure token\"\ncurl https://domain.tld/test8 -X GET -H \"Authorization: Bearer ${TOKEN}\""
        label: bash/curl
      - lang: php
        source: "$token = \"my secret token\";\n$url = \"https://domain.tld/test8\";\n$headers = array(\n    \"Authorization: \" . \"Bearer \" . $token,\n);\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST, \"GET\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_HTTPHEADER, $headers);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
        label: PHP
      - lang: js
        source: |-
          var token = "my secret token";
          var url = "https://domain.tld/test8";
          
          var request = new XMLHttpRequest();
          request.open("GET", url);
          request.setRequestHeader("Authorization", "Bearer " + token);
          
          request.send("");
          console.log(request.responseText);
        label: JavaScript
