components:
  schemas:
    Level1:
      properties:
        field1.1:
          $ref: '#/components/schemas/Level2'
        field1.2:
          format: int32
          type: integer
      required:
      - field1.2
      - field1.1
      type: object
    Level2:
      properties:
        field2.1:
          $ref: '#/components/schemas/Level3'
        field2.2:
          items:
            format: date-time
            type: string
          type: array
        field2.3:
          format: password
          type: string
      required:
      - field2.1
      - field2.2
      - field2.3
      type: object
    Level3:
      properties:
        field3.1:
          $ref: '#/components/schemas/Level4'
        field3.2:
          items:
            type: string
          type: array
      required:
      - field3.1
      - field3.2
      type: object
    Level4:
      properties:
        field4.1:
          items:
            $ref: '#/components/schemas/Level5'
          type: array
        field4.2:
          type: integer
      required:
      - field4.1
      - field4.2
      type: object
    Level5:
      properties:
        field5.1:
          enum:
          - "14"
          - a
          - b
          - c
          type: string
        field5.2:
          items:
            type: boolean
          type: array
        field5.3:
          type: string
        field5.4:
          type: number
      required:
      - field5.1
      - field5.2
      - field5.3
      - field5.4
      type: object
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test-form-data:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: OK
      x-codeSamples:
      - label: bash/curl
        lang: curl
        source: 'curl https://domain.tld/test-form-data -X POST -H "Content-Type:
          multipart/form-data boundary=7a42f46c1d826eab9db63f6613fa16df941f3bdfe17bb7d8250ccf7f61e4"
          -d "Content-Type: multipart/form-data; boundary=7a42f46c1d826eab9db63f6613fa16df941f3bdfe17bb7d8250ccf7f61e4\r\n\r\n--7a42f46c1d826eab9db63f6613fa16df941f3bdfe17bb7d8250ccf7f61e4\r\nContent-Id:
          field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=4a0e43b3cf2f4e5a95b6ea3d43e77d23ad07bed9aa8ac88b74d84948bfb8\r\n\r\n--4a0e43b3cf2f4e5a95b6ea3d43e77d23ad07bed9aa8ac88b74d84948bfb8\r\nContent-Id:
          field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--4a0e43b3cf2f4e5a95b6ea3d43e77d23ad07bed9aa8ac88b74d84948bfb8\r\nContent-Id:
          field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=ca2c71a9ac36b66b4cf515fbf787bdaf95a8318debfc9bf8c0677cbdc2e1\r\n\r\n--ca2c71a9ac36b66b4cf515fbf787bdaf95a8318debfc9bf8c0677cbdc2e1\r\nContent-Id:
          field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=ac687759849e6864bebcf1cb90db3ce15ed1593c190cccf12aeda9476c46\r\n\r\n--ac687759849e6864bebcf1cb90db3ce15ed1593c190cccf12aeda9476c46\r\nContent-Id:
          field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false]
          field5.3:example-string field5.4:1.234]]\r\n--ac687759849e6864bebcf1cb90db3ce15ed1593c190cccf12aeda9476c46\r\nContent-Id:
          field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--ac687759849e6864bebcf1cb90db3ce15ed1593c190cccf12aeda9476c46--\r\n\r\n--ca2c71a9ac36b66b4cf515fbf787bdaf95a8318debfc9bf8c0677cbdc2e1\r\nContent-Id:
          field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--ca2c71a9ac36b66b4cf515fbf787bdaf95a8318debfc9bf8c0677cbdc2e1--\r\n\r\n--4a0e43b3cf2f4e5a95b6ea3d43e77d23ad07bed9aa8ac88b74d84948bfb8\r\nContent-Id:
          field2.2\r\nContent-Type: text/plain\r\n\r\n[2022-05-22T13:33:42+02:00]\r\n--4a0e43b3cf2f4e5a95b6ea3d43e77d23ad07bed9aa8ac88b74d84948bfb8--\r\n\r\n--7a42f46c1d826eab9db63f6613fa16df941f3bdfe17bb7d8250ccf7f61e4\r\nContent-Id:
          field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--7a42f46c1d826eab9db63f6613fa16df941f3bdfe17bb7d8250ccf7f61e4--\r\n"'
      - label: PHP
        lang: php
        source: |-
          $url = "https://domain.tld/test-form-data";
          $data = "Content-Type: multipart/form-data; boundary=593b9f599a2b37dfaa621cd138bff290c5e9d106b08fc3d656fd603f6c0d\r\n\r\n--593b9f599a2b37dfaa621cd138bff290c5e9d106b08fc3d656fd603f6c0d\r\nContent-Id: field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=6aec034e5c405402d1889cc829afc6c471328c69a35463dee4deab07c9fe\r\n\r\n--6aec034e5c405402d1889cc829afc6c471328c69a35463dee4deab07c9fe\r\nContent-Id: field2.2\r\nContent-Type: text/plain\r\n\r\n[2022-05-22T13:33:42+02:00]\r\n--6aec034e5c405402d1889cc829afc6c471328c69a35463dee4deab07c9fe\r\nContent-Id: field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--6aec034e5c405402d1889cc829afc6c471328c69a35463dee4deab07c9fe\r\nContent-Id: field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=4bf26f80d280908f80acc74a6ca365626e01b50221ca4e4d0041031920e9\r\n\r\n--4bf26f80d280908f80acc74a6ca365626e01b50221ca4e4d0041031920e9\r\nContent-Id: field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=79ca94e144a630ecb3ab18fbca2d5580c252d837fefa7da211cd6a28ad99\r\n\r\n--79ca94e144a630ecb3ab18fbca2d5580c252d837fefa7da211cd6a28ad99\r\nContent-Id: field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false] field5.3:example-string field5.4:1.234]]\r\n--79ca94e144a630ecb3ab18fbca2d5580c252d837fefa7da211cd6a28ad99\r\nContent-Id: field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--79ca94e144a630ecb3ab18fbca2d5580c252d837fefa7da211cd6a28ad99--\r\n\r\n--4bf26f80d280908f80acc74a6ca365626e01b50221ca4e4d0041031920e9\r\nContent-Id: field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--4bf26f80d280908f80acc74a6ca365626e01b50221ca4e4d0041031920e9--\r\n\r\n--6aec034e5c405402d1889cc829afc6c471328c69a35463dee4deab07c9fe--\r\n\r\n--593b9f599a2b37dfaa621cd138bff290c5e9d106b08fc3d656fd603f6c0d\r\nContent-Id: field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--593b9f599a2b37dfaa621cd138bff290c5e9d106b08fc3d656fd603f6c0d--\r\n";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
      - label: JavaScript
        lang: js
        source: |2-

          var url = "https://domain.tld/test-form-data";

          var request = new XMLHttpRequest();
          request.open("POST", url);
          request.setRequestHeader("Content-Type", "multipart/form-data boundary=61f651972bc8a07e2eac238b0cf2ca2d28e2645fa46446bb217ee5310235");

          request.send("Content-Type: multipart/form-data; boundary=61f651972bc8a07e2eac238b0cf2ca2d28e2645fa46446bb217ee5310235\r\n\r\n--61f651972bc8a07e2eac238b0cf2ca2d28e2645fa46446bb217ee5310235\r\nContent-Id: field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=451af95568126284a741da353430341b82f822e420b773187562b0566809\r\n\r\n--451af95568126284a741da353430341b82f822e420b773187562b0566809\r\nContent-Id: field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--451af95568126284a741da353430341b82f822e420b773187562b0566809\r\nContent-Id: field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=d36120eb66a617b2102883d0a834db36824490f3aa684b6020dccb4f13ad\r\n\r\n--d36120eb66a617b2102883d0a834db36824490f3aa684b6020dccb4f13ad\r\nContent-Id: field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=a0d4d7fe12a88e1a6a7ff3deaf1b01d2cafd3fb1e9828cd23e6d058a5c90\r\n\r\n--a0d4d7fe12a88e1a6a7ff3deaf1b01d2cafd3fb1e9828cd23e6d058a5c90\r\nContent-Id: field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false] field5.3:example-string field5.4:1.234]]\r\n--a0d4d7fe12a88e1a6a7ff3deaf1b01d2cafd3fb1e9828cd23e6d058a5c90\r\nContent-Id: field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--a0d4d7fe12a88e1a6a7ff3deaf1b01d2cafd3fb1e9828cd23e6d058a5c90--\r\n\r\n--d36120eb66a617b2102883d0a834db36824490f3aa684b6020dccb4f13ad\r\nContent-Id: field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--d36120eb66a617b2102883d0a834db36824490f3aa684b6020dccb4f13ad--\r\n\r\n--451af95568126284a741da353430341b82f822e420b773187562b0566809\r\nContent-Id: field2.2\r\nContent-Type: text/plain\r\n\r\n[2022-05-22T13:33:42+02:00]\r\n--451af95568126284a741da353430341b82f822e420b773187562b0566809--\r\n\r\n--61f651972bc8a07e2eac238b0cf2ca2d28e2645fa46446bb217ee5310235\r\nContent-Id: field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--61f651972bc8a07e2eac238b0cf2ca2d28e2645fa46446bb217ee5310235--\r\n");
          console.log(request.responseText);
  /test-json:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: |
            ok
      x-codeSamples:
      - label: bash/curl
        lang: curl
        source: 'curl https://domain.tld/test-json -X POST -H "Content-Type: application/json
          " -d "{\"field1.1\":{\"field2.1\":{\"field3.1\":{\"field4.1\":[{\"field5.1\":\"14\",\"field5.2\":[false],\"field5.3\":\"example-string\",\"field5.4\":1.234}],\"field4.2\":1234},\"field3.2\":[\"example-string\"]},\"field2.2\":[\"2022-05-22T13:33:42+02:00\"],\"field2.3\":\"example-string\"},\"field1.2\":1234}"'
      - label: PHP
        lang: php
        source: "$url = \"https://domain.tld/test-json\";\n$data = json_encode(array(\n\t\"field1.1\"
          => array(\n\t\t\"field2.2\" => array(\n\t\t\t\"2022-05-22T13:33:42+02:00\",\n\t\t),\n\t\t\"field2.3\"
          => \"example-string\",\n\t\t\"field2.1\" => array(\n\t\t\t\"field3.1\" =>
          array(\n\t\t\t\t\"field4.1\" => array(\n\t\t\t\t\tarray(\n\t\t\t\t\t\t\"field5.1\"
          => \"14\",\n\t\t\t\t\t\t\"field5.2\" => array(\n\t\t\t\t\t\t\tfalse,\n\t\t\t\t\t\t),\n\t\t\t\t\t\t\"field5.3\"
          => \"example-string\",\n\t\t\t\t\t\t\"field5.4\" => \"1.234\",\n\t\t\t\t\t),\n\t\t\t\t),\n\t\t\t\t\"field4.2\"
          => \"1234\",\n\t\t\t),\n\t\t\t\"field3.2\" => array(\n\t\t\t\t\"example-string\",\n\t\t\t),\n\t\t),\n\t),\n\t\"field1.2\"
          => \"1234\",\n));\n\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST,
          \"POST\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl,
          CURLOPT_POSTFIELDS, $data);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
      - label: JavaScript
        lang: js
        source: |2-

          var url = "https://domain.tld/test-json";

          var request = new XMLHttpRequest();
          request.open("POST", url);
          request.setRequestHeader("Content-Type", "application/json");

          request.send("{\"field1.1\":{\"field2.1\":{\"field3.1\":{\"field4.1\":[{\"field5.1\":\"14\",\"field5.2\":[false],\"field5.3\":\"example-string\",\"field5.4\":1.234}],\"field4.2\":1234},\"field3.2\":[\"example-string\"]},\"field2.2\":[\"2022-05-22T13:33:42+02:00\"],\"field2.3\":\"example-string\"},\"field1.2\":1234}");
          console.log(request.responseText);
  /test-xml:
    post:
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: ok
      x-codeSamples:
      - label: bash/curl
        lang: curl
        source: 'curl https://domain.tld/test-xml -X POST -H "Content-Type: text/xml
          " -d "<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-05-22T13:33:42+02:00</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>"'
      - label: PHP
        lang: php
        source: |-
          $url = "https://domain.tld/test-xml";
          $data = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-05-22T13:33:42+02:00</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
      - label: JavaScript
        lang: js
        source: |2-

          var url = "https://domain.tld/test-xml";

          var request = new XMLHttpRequest();
          request.open("POST", url);
          request.setRequestHeader("Content-Type", "text/xml");

          request.send("<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-05-22T13:33:42+02:00</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>");
          console.log(request.responseText);
