components:
  schemas:
    Level1:
      properties:
        field1.1:
          $ref: '#/components/schemas/Level2'
        field1.2:
          format: int32
          type: integer
      required:
      - field1.2
      - field1.1
      type: object
    Level2:
      properties:
        field2.1:
          $ref: '#/components/schemas/Level3'
        field2.2:
          items:
            format: date-time
            type: string
          type: array
        field2.3:
          format: password
          type: string
      required:
      - field2.1
      - field2.2
      - field2.3
      type: object
    Level3:
      properties:
        field3.1:
          $ref: '#/components/schemas/Level4'
        field3.2:
          items:
            type: string
          type: array
      required:
      - field3.1
      - field3.2
      type: object
    Level4:
      properties:
        field4.1:
          items:
            $ref: '#/components/schemas/Level5'
          type: array
        field4.2:
          type: integer
      required:
      - field4.1
      - field4.2
      type: object
    Level5:
      properties:
        field5.1:
          enum:
          - "14"
          - a
          - b
          - c
          type: string
        field5.2:
          items:
            type: boolean
          type: array
        field5.3:
          type: string
        field5.4:
          type: number
      required:
      - field5.1
      - field5.2
      - field5.3
      - field5.4
      type: object
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test-form-data:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: OK
      x-codeSamples:
      - label: curl
        lang: curl
        source: 'curl "domain.tld/test-form-data" -d "Content-Type: multipart/form-data;
          boundary=fc177bc9c295f9dea7583d8c699f5ac06e778b153be3dd2be172df17111c\r\n\r\n--fc177bc9c295f9dea7583d8c699f5ac06e778b153be3dd2be172df17111c\r\nContent-Id:
          field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=7e59dbe79cb8b07c7638c105e562a0da8801f1f1118f097accf6caf87360\r\n\r\n--7e59dbe79cb8b07c7638c105e562a0da8801f1f1118f097accf6caf87360\r\nContent-Id:
          field2.2\r\nContent-Type: text/plain\r\n\r\n[2021-12-17T19:03:08+01:00]\r\n--7e59dbe79cb8b07c7638c105e562a0da8801f1f1118f097accf6caf87360\r\nContent-Id:
          field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--7e59dbe79cb8b07c7638c105e562a0da8801f1f1118f097accf6caf87360\r\nContent-Id:
          field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=01886267ebbb80e48d4f79d028333c01f3bbead63dc36b819310beda7bb6\r\n\r\n--01886267ebbb80e48d4f79d028333c01f3bbead63dc36b819310beda7bb6\r\nContent-Id:
          field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=12a30829bff815b9c959d2377300016b23b633ff9983636edd67a58871ba\r\n\r\n--12a30829bff815b9c959d2377300016b23b633ff9983636edd67a58871ba\r\nContent-Id:
          field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false]
          field5.3:example-string field5.4:1.234]]\r\n--12a30829bff815b9c959d2377300016b23b633ff9983636edd67a58871ba\r\nContent-Id:
          field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--12a30829bff815b9c959d2377300016b23b633ff9983636edd67a58871ba--\r\n\r\n--01886267ebbb80e48d4f79d028333c01f3bbead63dc36b819310beda7bb6\r\nContent-Id:
          field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--01886267ebbb80e48d4f79d028333c01f3bbead63dc36b819310beda7bb6--\r\n\r\n--7e59dbe79cb8b07c7638c105e562a0da8801f1f1118f097accf6caf87360--\r\n\r\n--fc177bc9c295f9dea7583d8c699f5ac06e778b153be3dd2be172df17111c\r\nContent-Id:
          field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--fc177bc9c295f9dea7583d8c699f5ac06e778b153be3dd2be172df17111c--\r\n"
          -H "Content-Type: multipart/form-data boundary=fc177bc9c295f9dea7583d8c699f5ac06e778b153be3dd2be172df17111c"
          -X POST'
      - label: PHP
        lang: php
        source: "<?php\n$url = \"domain.tld/test-form-data\";\n$data = \"Content-Type:
          multipart/form-data; boundary=f81779ccba949b72e22563e7966393856d9db5eb801185069372822a3463\\r\\n\\r\\n--f81779ccba949b72e22563e7966393856d9db5eb801185069372822a3463\\r\\nContent-Id:
          field1.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data;
          boundary=38ab66f6bb8e72eefc8e2085619190782e74621c19c2f12178703efff628\\r\\n\\r\\n--38ab66f6bb8e72eefc8e2085619190782e74621c19c2f12178703efff628\\r\\nContent-Id:
          field2.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[2021-12-17T19:03:08+01:00]\\r\\n--38ab66f6bb8e72eefc8e2085619190782e74621c19c2f12178703efff628\\r\\nContent-Id:
          field2.3\\r\\nContent-Type: text/plain\\r\\n\\r\\nexample-string\\r\\n--38ab66f6bb8e72eefc8e2085619190782e74621c19c2f12178703efff628\\r\\nContent-Id:
          field2.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data;
          boundary=b14eb11085f6ddec61aa982a825ada2dae1f692bedf180bc4417298d7146\\r\\n\\r\\n--b14eb11085f6ddec61aa982a825ada2dae1f692bedf180bc4417298d7146\\r\\nContent-Id:
          field3.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[example-string]\\r\\n--b14eb11085f6ddec61aa982a825ada2dae1f692bedf180bc4417298d7146\\r\\nContent-Id:
          field3.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data;
          boundary=eccfdf328571e269a3c52b7f3809280179dc92f5afd16a74c3ae07192fc9\\r\\n\\r\\n--eccfdf328571e269a3c52b7f3809280179dc92f5afd16a74c3ae07192fc9\\r\\nContent-Id:
          field4.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--eccfdf328571e269a3c52b7f3809280179dc92f5afd16a74c3ae07192fc9\\r\\nContent-Id:
          field4.1\\r\\nContent-Type: text/plain\\r\\n\\r\\n[map[field5.1:14 field5.2:[false]
          field5.3:example-string field5.4:1.234]]\\r\\n--eccfdf328571e269a3c52b7f3809280179dc92f5afd16a74c3ae07192fc9--\\r\\n\\r\\n--b14eb11085f6ddec61aa982a825ada2dae1f692bedf180bc4417298d7146--\\r\\n\\r\\n--38ab66f6bb8e72eefc8e2085619190782e74621c19c2f12178703efff628--\\r\\n\\r\\n--f81779ccba949b72e22563e7966393856d9db5eb801185069372822a3463\\r\\nContent-Id:
          field1.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--f81779ccba949b72e22563e7966393856d9db5eb801185069372822a3463--\\r\\n\";\n$headers
          = array(\n\t\"Content-Type: multipart/form-data boundary=f81779ccba949b72e22563e7966393856d9db5eb801185069372822a3463\",\n);\n\n\n$curl
          = curl_init($url);\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl,
          CURLOPT_POSTFIELDS, $data);\ncurl_setopt($curl, CURLOPT_HTTPHEADER, $headers);\ncurl_setopt($curl,
          CURLOPT_CUSTOMREQUEST, 'POST');\nvar_dump(curl_exec($curl)); // Dumps the
          response\ncurl_close($curl);"
  /test-json:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: |
            ok
      x-codeSamples:
      - label: curl
        lang: curl
        source: 'curl "domain.tld/test-json" -d "{\"field1.1\":{\"field2.1\":{\"field3.1\":{\"field4.1\":[{\"field5.1\":\"14\",\"field5.2\":[false],\"field5.3\":\"example-string\",\"field5.4\":1.234}],\"field4.2\":1234},\"field3.2\":[\"example-string\"]},\"field2.2\":[\"2021-12-17T19:03:08+01:00\"],\"field2.3\":\"example-string\"},\"field1.2\":1234}"
          -H "Content-Type: application/json" -X POST'
      - label: PHP
        lang: php
        source: "<?php\n$url = \"domain.tld/test-json\";\n$data = json_encode(array(\n\t\"field1.1\"
          => array(\n\t\t\"field2.1\" => array(\n\t\t\t\"field3.2\" => array(\n\t\t\t\t\"example-string\",\n\t\t\t),\n\t\t\t\"field3.1\"
          => array(\n\t\t\t\t\"field4.2\" => \"1234\",\n\t\t\t\t\"field4.1\" => array(\n\t\t\t\t\tarray(\n\t\t\t\t\t\t\"field5.1\"
          => \"14\",\n\t\t\t\t\t\t\"field5.2\" => array(\n\t\t\t\t\t\t\tfalse,\n\t\t\t\t\t\t),\n\t\t\t\t\t\t\"field5.3\"
          => \"example-string\",\n\t\t\t\t\t\t\"field5.4\" => \"1.234\",\n\t\t\t\t\t),\n\t\t\t\t),\n\t\t\t),\n\t\t),\n\t\t\"field2.2\"
          => array(\n\t\t\t\"2021-12-17T19:03:08+01:00\",\n\t\t),\n\t\t\"field2.3\"
          => \"example-string\",\n\t),\n\t\"field1.2\" => \"1234\",\n));\n$headers
          = array(\n\t\"Content-Type: application/json\",\n);\n\n\n$curl = curl_init($url);\ncurl_setopt($curl,
          CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_POSTFIELDS, $data);\ncurl_setopt($curl,
          CURLOPT_HTTPHEADER, $headers);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST,
          'POST');\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
  /test-xml:
    post:
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: ok
      x-codeSamples:
      - label: curl
        lang: curl
        source: 'curl "domain.tld/test-xml" -d "<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2021-12-17T19:03:08+01:00</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>"
          -H "Content-Type: text/xml" -X POST'
      - label: PHP
        lang: php
        source: "<?php\n$url = \"domain.tld/test-xml\";\n$data = \"<?xml version=\\\"1.0\\\"
          encoding=\\\"UTF-8\\\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2021-12-17T19:03:08+01:00</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>\";\n$headers
          = array(\n\t\"Content-Type: text/xml\",\n);\n\n\n$curl = curl_init($url);\ncurl_setopt($curl,
          CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_POSTFIELDS, $data);\ncurl_setopt($curl,
          CURLOPT_HTTPHEADER, $headers);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST,
          'POST');\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
