components:
  schemas:
    Level1:
      properties:
        field1.1:
          $ref: "#/components/schemas/Level2"
        field1.2:
          format: int32
          type: integer
      required:
      - field1.2
      - field1.1
      type: object
    Level2:
      properties:
        field2.1:
          $ref: "#/components/schemas/Level3"
        field2.2:
          items:
            format: date-time
            type: string
          type: array
        field2.3:
          format: password
          type: string
      required:
      - field2.1
      - field2.2
      - field2.3
      type: object
    Level3:
      properties:
        field3.1:
          $ref: "#/components/schemas/Level4"
        field3.2:
          items:
            type: string
          type: array
      required:
      - field3.1
      - field3.2
      type: object
    Level4:
      properties:
        field4.1:
          items:
            $ref: "#/components/schemas/Level5"
          type: array
        field4.2:
          type: integer
      required:
      - field4.1
      - field4.2
      type: object
    Level5:
      properties:
        field5.1:
          enum:
          - "14"
          - a
          - b
          - c
          type: string
        field5.2:
          items:
            type: boolean
          type: array
        field5.3:
          type: string
        field5.4:
          type: number
      required:
      - field5.1
      - field5.2
      - field5.3
      - field5.4
      type: object
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test-form-data:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Level1"
        required: true
      responses:
        "200":
          description: OK
      x-codeSamples:
      - lang: curl
        source: "curl https://domain.tld/test-form-data -X POST -H \"Content-Type: multipart/form-data boundary=ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\" -d \"Content-Type: multipart/form-data; boundary=ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\n\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\nContent-Id: field1.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\n\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[2022-01-01T15:00:14Z]\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.3\\r\\nContent-Type: text/plain\\r\\n\\r\\nexample-string\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\n\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\nContent-Id: field3.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\n\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\nContent-Id: field4.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\nContent-Id: field4.1\\r\\nContent-Type: text/plain\\r\\n\\r\\n[map[field5.1:14 field5.2:[false] field5.3:example-string field5.4:1.234]]\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1--\\r\\n\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\nContent-Id: field3.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[example-string]\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i--\\r\\n\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h--\\r\\n\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\nContent-Id: field1.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee--\\r\\n\""
        label: bash/curl
      - lang: php
        source: "$url = \"https://domain.tld/test-form-data\";\n$data = \"Content-Type: multipart/form-data; boundary=ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\n\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\nContent-Id: field1.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\n\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.3\\r\\nContent-Type: text/plain\\r\\n\\r\\nexample-string\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\n\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\nContent-Id: field3.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\n\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\nContent-Id: field4.1\\r\\nContent-Type: text/plain\\r\\n\\r\\n[map[field5.1:14 field5.2:[false] field5.3:example-string field5.4:1.234]]\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\nContent-Id: field4.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1--\\r\\n\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\nContent-Id: field3.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[example-string]\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i--\\r\\n\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[2022-01-01T15:00:14Z]\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h--\\r\\n\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\nContent-Id: field1.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee--\\r\\n\";\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST, \"POST\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_POSTFIELDS, $data);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
        label: PHP
      - lang: js
        source: "\nvar url = \"https://domain.tld/test-form-data\";\n\nvar request = new XMLHttpRequest();\nrequest.open(\"POST\", url);\nrequest.setRequestHeader(\"Content-Type\", \"multipart/form-data boundary=ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\");\n\nrequest.send(\"Content-Type: multipart/form-data; boundary=ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\n\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\nContent-Id: field1.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\n\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\n\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\nContent-Id: field3.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[example-string]\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i\\r\\nContent-Id: field3.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data; boundary=ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\n\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\nContent-Id: field4.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1\\r\\nContent-Id: field4.1\\r\\nContent-Type: text/plain\\r\\n\\r\\n[map[field5.1:14 field5.2:[false] field5.3:example-string field5.4:1.234]]\\r\\n--ul9ni9is2aiPhie7comejaW7eeb2sheekaaP9na2UXaPuh4pez9kein0aiw1--\\r\\n\\r\\n--iesh2FoonaloPhic0wohs8aey7thie0tuofahy8ahsh1unaeQueifohmoh5i--\\r\\n\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[2022-01-01T15:00:14Z]\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h\\r\\nContent-Id: field2.3\\r\\nContent-Type: text/plain\\r\\n\\r\\nexample-string\\r\\n--oviongienesei6eel0uqueipungaixaecoh4wiezighahPh9aiShiokahy6h--\\r\\n\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee\\r\\nContent-Id: field1.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--ueng3raexexiFah9xae6keejie1oac7aid8thoe2aineiw4ohcip6aef4kee--\\r\\n\");\nconsole.log(request.responseText);"
        label: JavaScript
  /test-json:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Level1"
        required: true
      responses:
        "200":
          description: |
            ok
      x-codeSamples:
      - lang: curl
        source: "curl https://domain.tld/test-json -X POST -H \"Content-Type: application/json \" -d \"{\\\"field1.1\\\":{\\\"field2.1\\\":{\\\"field3.1\\\":{\\\"field4.1\\\":[{\\\"field5.1\\\":\\\"14\\\",\\\"field5.2\\\":[false],\\\"field5.3\\\":\\\"example-string\\\",\\\"field5.4\\\":1.234}],\\\"field4.2\\\":1234},\\\"field3.2\\\":[\\\"example-string\\\"]},\\\"field2.2\\\":[\\\"2022-01-01T15:00:14Z\\\"],\\\"field2.3\\\":\\\"example-string\\\"},\\\"field1.2\\\":1234}\""
        label: bash/curl
      - lang: php
        source: |-
          $url = "https://domain.tld/test-json";
          $data = json_encode(array(
          	"field1.1" => array(
          		"field2.1" => array(
          			"field3.2" => array(
          				"example-string",
          			),
          			"field3.1" => array(
          				"field4.1" => array(
          					array(
          						"field5.1" => "14",
          						"field5.2" => array(
          							false,
          						),
          						"field5.3" => "example-string",
          						"field5.4" => "1.234",
          					),
          				),
          				"field4.2" => "1234",
          			),
          		),
          		"field2.2" => array(
          			"2022-01-01T15:00:14Z",
          		),
          		"field2.3" => "example-string",
          	),
          	"field1.2" => "1234",
          ));
          
          
          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
        label: PHP
      - lang: js
        source: "\nvar url = \"https://domain.tld/test-json\";\n\nvar request = new XMLHttpRequest();\nrequest.open(\"POST\", url);\nrequest.setRequestHeader(\"Content-Type\", \"application/json\");\n\nrequest.send({\n\t\"field1.1\": {\n\t\t\"field2.1\": {\n\t\t\t\"field3.1\": {\n\t\t\t\t\"field4.1\": [\n\t\t\t\t\t{\n\t\t\t\t\t\t\"field5.1\": \"14\",\n\t\t\t\t\t\t\"field5.2\": [\n\t\t\t\t\t\t\tfalse\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"field5.3\": \"example-string\",\n\t\t\t\t\t\t\"field5.4\": 1.234\n\t\t\t\t\t}\n\t\t\t\t],\n\t\t\t\t\"field4.2\": 1234\n\t\t\t},\n\t\t\t\"field3.2\": [\n\t\t\t\t\"example-string\"\n\t\t\t]\n\t\t},\n\t\t\"field2.2\": [\n\t\t\t\"2022-01-01T15:00:14Z\"\n\t\t],\n\t\t\"field2.3\": \"example-string\"\n\t},\n\t\"field1.2\": 1234\n});\nconsole.log(request.responseText);"
        label: JavaScript
  /test-xml:
    post:
      requestBody:
        content:
          text/xml:
            schema:
              $ref: "#/components/schemas/Level1"
        required: true
      responses:
        "200":
          description: ok
      x-codeSamples:
      - lang: curl
        source: "curl https://domain.tld/test-xml -X POST -H \"Content-Type: text/xml \" -d \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-01-01T15:00:14Z</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>\""
        label: bash/curl
      - lang: php
        source: "$url = \"https://domain.tld/test-xml\";\n$data = \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-01-01T15:00:14Z</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>\";\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST, \"POST\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_POSTFIELDS, $data);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
        label: PHP
      - lang: js
        source: "\nvar url = \"https://domain.tld/test-xml\";\n\nvar request = new XMLHttpRequest();\nrequest.open(\"POST\", url);\nrequest.setRequestHeader(\"Content-Type\", \"text/xml\");\n\nrequest.send(\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-01-01T15:00:14Z</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>\");\nconsole.log(request.responseText);"
        label: JavaScript
