components:
  schemas:
    Level1:
      properties:
        field1.1:
          $ref: '#/components/schemas/Level2'
        field1.2:
          format: int32
          type: integer
      required:
      - field1.2
      - field1.1
      type: object
    Level2:
      properties:
        field2.1:
          $ref: '#/components/schemas/Level3'
        field2.2:
          items:
            format: date-time
            type: string
          type: array
        field2.3:
          format: password
          type: string
      required:
      - field2.1
      - field2.2
      - field2.3
      type: object
    Level3:
      properties:
        field3.1:
          $ref: '#/components/schemas/Level4'
        field3.2:
          items:
            type: string
          type: array
      required:
      - field3.1
      - field3.2
      type: object
    Level4:
      properties:
        field4.1:
          items:
            $ref: '#/components/schemas/Level5'
          type: array
        field4.2:
          type: integer
      required:
      - field4.1
      - field4.2
      type: object
    Level5:
      properties:
        field5.1:
          enum:
          - "14"
          - a
          - b
          - c
          type: string
        field5.2:
          items:
            type: boolean
          type: array
        field5.3:
          type: string
        field5.4:
          type: number
      required:
      - field5.1
      - field5.2
      - field5.3
      - field5.4
      type: object
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test-form-data:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: OK
      x-codeSamples:
      - label: curl
        lang: curl
        source: 'curl "domain.tld/test-form-data" -d "Content-Type: multipart/form-data;
          boundary=fffa52919450b34d896d6273bf5ba1d9457162e81e8ad58875f94fdda7f4\r\n\r\n--fffa52919450b34d896d6273bf5ba1d9457162e81e8ad58875f94fdda7f4\r\nContent-Id:
          field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=5522a37d2ed13b85273ff8c5a5463287a38114a5025cb143eb39b1bde232\r\n\r\n--5522a37d2ed13b85273ff8c5a5463287a38114a5025cb143eb39b1bde232\r\nContent-Id:
          field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=aef4c04589caf5bab34190f1ec9a3bc8ea9d0968130d37cec756d6e25506\r\n\r\n--aef4c04589caf5bab34190f1ec9a3bc8ea9d0968130d37cec756d6e25506\r\nContent-Id:
          field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=84e47e7b3e08400681fcb27da1970a20e2e7f6b2c76b1b1dd152504b68ce\r\n\r\n--84e47e7b3e08400681fcb27da1970a20e2e7f6b2c76b1b1dd152504b68ce\r\nContent-Id:
          field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false]
          field5.3:example-string field5.4:1.234]]\r\n--84e47e7b3e08400681fcb27da1970a20e2e7f6b2c76b1b1dd152504b68ce\r\nContent-Id:
          field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--84e47e7b3e08400681fcb27da1970a20e2e7f6b2c76b1b1dd152504b68ce--\r\n\r\n--aef4c04589caf5bab34190f1ec9a3bc8ea9d0968130d37cec756d6e25506\r\nContent-Id:
          field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--aef4c04589caf5bab34190f1ec9a3bc8ea9d0968130d37cec756d6e25506--\r\n\r\n--5522a37d2ed13b85273ff8c5a5463287a38114a5025cb143eb39b1bde232\r\nContent-Id:
          field2.2\r\nContent-Type: text/plain\r\n\r\n[2021-12-17T18:58:47+01:00]\r\n--5522a37d2ed13b85273ff8c5a5463287a38114a5025cb143eb39b1bde232\r\nContent-Id:
          field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--5522a37d2ed13b85273ff8c5a5463287a38114a5025cb143eb39b1bde232--\r\n\r\n--fffa52919450b34d896d6273bf5ba1d9457162e81e8ad58875f94fdda7f4\r\nContent-Id:
          field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--fffa52919450b34d896d6273bf5ba1d9457162e81e8ad58875f94fdda7f4--\r\n"
          -H "Content-Type: multipart/form-data boundary=fffa52919450b34d896d6273bf5ba1d9457162e81e8ad58875f94fdda7f4"
          -X POST'
      - label: PHP
        lang: php
        source: "<?php\n$url = \"domain.tld/test-form-data\";\n$data = \"Content-Type:
          multipart/form-data; boundary=8003c5d6bb2e1ef0a2fcaa750520bc27cdd7a8c5bcbbc76e0ead517485b8\\r\\n\\r\\n--8003c5d6bb2e1ef0a2fcaa750520bc27cdd7a8c5bcbbc76e0ead517485b8\\r\\nContent-Id:
          field1.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data;
          boundary=7ef9b17e44a8c165c9c54a6814cde474a14234f6bba7d2242484b2c61524\\r\\n\\r\\n--7ef9b17e44a8c165c9c54a6814cde474a14234f6bba7d2242484b2c61524\\r\\nContent-Id:
          field2.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data;
          boundary=09de9a758f4c524fa54d3f63f3ecf3c9cb82652b77792c09311b1a037c52\\r\\n\\r\\n--09de9a758f4c524fa54d3f63f3ecf3c9cb82652b77792c09311b1a037c52\\r\\nContent-Id:
          field3.1\\r\\nContent-Type: text/plain\\r\\n\\r\\nContent-Type: multipart/form-data;
          boundary=2d9ed4ce8327224529b96b01dc1515f08d240c888e782911ffaa1c102b65\\r\\n\\r\\n--2d9ed4ce8327224529b96b01dc1515f08d240c888e782911ffaa1c102b65\\r\\nContent-Id:
          field4.1\\r\\nContent-Type: text/plain\\r\\n\\r\\n[map[field5.1:14 field5.2:[false]
          field5.3:example-string field5.4:1.234]]\\r\\n--2d9ed4ce8327224529b96b01dc1515f08d240c888e782911ffaa1c102b65\\r\\nContent-Id:
          field4.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--2d9ed4ce8327224529b96b01dc1515f08d240c888e782911ffaa1c102b65--\\r\\n\\r\\n--09de9a758f4c524fa54d3f63f3ecf3c9cb82652b77792c09311b1a037c52\\r\\nContent-Id:
          field3.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[example-string]\\r\\n--09de9a758f4c524fa54d3f63f3ecf3c9cb82652b77792c09311b1a037c52--\\r\\n\\r\\n--7ef9b17e44a8c165c9c54a6814cde474a14234f6bba7d2242484b2c61524\\r\\nContent-Id:
          field2.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n[2021-12-17T18:58:47+01:00]\\r\\n--7ef9b17e44a8c165c9c54a6814cde474a14234f6bba7d2242484b2c61524\\r\\nContent-Id:
          field2.3\\r\\nContent-Type: text/plain\\r\\n\\r\\nexample-string\\r\\n--7ef9b17e44a8c165c9c54a6814cde474a14234f6bba7d2242484b2c61524--\\r\\n\\r\\n--8003c5d6bb2e1ef0a2fcaa750520bc27cdd7a8c5bcbbc76e0ead517485b8\\r\\nContent-Id:
          field1.2\\r\\nContent-Type: text/plain\\r\\n\\r\\n1234\\r\\n--8003c5d6bb2e1ef0a2fcaa750520bc27cdd7a8c5bcbbc76e0ead517485b8--\\r\\n\";\n$headers
          = array(\n\t\"Content-Type: multipart/form-data boundary=8003c5d6bb2e1ef0a2fcaa750520bc27cdd7a8c5bcbbc76e0ead517485b8\",\n);\n\n\n$curl
          = curl_init($url);\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl,
          CURLOPT_POSTFIELDS, $data);\ncurl_setopt($curl, CURLOPT_HTTPHEADER, $headers);\ncurl_setopt($curl,
          CURLOPT_CUSTOMREQUEST, 'POST');\nvar_dump(curl_exec($curl)); // Dumps the
          response\ncurl_close($curl);"
  /test-json:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: |
            ok
      x-codeSamples:
      - label: curl
        lang: curl
        source: 'curl "domain.tld/test-json" -d "{\"field1.1\":{\"field2.1\":{\"field3.1\":{\"field4.1\":[{\"field5.1\":\"14\",\"field5.2\":[false],\"field5.3\":\"example-string\",\"field5.4\":1.234}],\"field4.2\":1234},\"field3.2\":[\"example-string\"]},\"field2.2\":[\"2021-12-17T18:58:47+01:00\"],\"field2.3\":\"example-string\"},\"field1.2\":1234}"
          -H "Content-Type: application/json" -X POST'
      - label: PHP
        lang: php
        source: "<?php\n$url = \"domain.tld/test-json\";\n$data = json_encode(array(\n\t\"field1.1\"
          => array(\n\n\t\"field2.2\" => array(\n\n\n\n\t\"2021-12-17T18:58:47+01:00\",\n\n\n\n),\n\n\t\"field2.3\"
          => \"example-string\",\n\n\t\"field2.1\" => array(\n\n\n\n\t\"field3.1\"
          => array(\n\n\n\n\n\n\n\n\t\"field4.2\" => \"1234\",\n\n\n\n\n\n\n\n\t\"field4.1\"
          => array(\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\tarray(\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\"field5.1\"
          => \"14\",\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\"field5.2\"
          => array(\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\tfalse,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\"field5.3\"
          => \"example-string\",\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\"field5.4\"
          => \"1.234\",\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n),\n\n\n\n\n\n\n\n),\n\n\n\n\t\"field3.2\"
          => array(\n\n\n\n\n\n\n\n\t\"example-string\",\n\n\n\n\n\n\n\n),\n\n\n\n),\n\n),\n\t\"field1.2\"
          => \"1234\",\n));\n$headers = array(\n\t\"Content-Type: application/json\",\n);\n\n\n$curl
          = curl_init($url);\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl,
          CURLOPT_POSTFIELDS, $data);\ncurl_setopt($curl, CURLOPT_HTTPHEADER, $headers);\ncurl_setopt($curl,
          CURLOPT_CUSTOMREQUEST, 'POST');\nvar_dump(curl_exec($curl)); // Dumps the
          response\ncurl_close($curl);"
  /test-xml:
    post:
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: ok
      x-codeSamples:
      - label: curl
        lang: curl
        source: 'curl "domain.tld/test-xml" -d "<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2021-12-17T18:58:47+01:00</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>"
          -H "Content-Type: text/xml" -X POST'
      - label: PHP
        lang: php
        source: "<?php\n$url = \"domain.tld/test-xml\";\n$data = \"<?xml version=\\\"1.0\\\"
          encoding=\\\"UTF-8\\\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2021-12-17T18:58:47+01:00</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>\";\n$headers
          = array(\n\t\"Content-Type: text/xml\",\n);\n\n\n$curl = curl_init($url);\ncurl_setopt($curl,
          CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl, CURLOPT_POSTFIELDS, $data);\ncurl_setopt($curl,
          CURLOPT_HTTPHEADER, $headers);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST,
          'POST');\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
