components:
  schemas:
    Level1:
      properties:
        field1.1:
          $ref: '#/components/schemas/Level2'
        field1.2:
          format: int32
          type: integer
      required:
      - field1.2
      - field1.1
      type: object
    Level2:
      properties:
        field2.1:
          $ref: '#/components/schemas/Level3'
        field2.2:
          items:
            format: date-time
            type: string
          type: array
        field2.3:
          format: password
          type: string
      required:
      - field2.1
      - field2.2
      - field2.3
      type: object
    Level3:
      properties:
        field3.1:
          $ref: '#/components/schemas/Level4'
        field3.2:
          items:
            type: string
          type: array
      required:
      - field3.1
      - field3.2
      type: object
    Level4:
      properties:
        field4.1:
          items:
            $ref: '#/components/schemas/Level5'
          type: array
        field4.2:
          type: integer
      required:
      - field4.1
      - field4.2
      type: object
    Level5:
      properties:
        field5.1:
          enum:
          - "14"
          - a
          - b
          - c
          type: string
        field5.2:
          items:
            type: boolean
          type: array
        field5.3:
          type: string
        field5.4:
          type: number
      required:
      - field5.1
      - field5.2
      - field5.3
      - field5.4
      type: object
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test-form-data:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: OK
      x-codeSamples:
      - label: bash/curl
        lang: curl
        source: 'curl https://domain.tld/test-form-data -X POST -H "Content-Type:
          multipart/form-data boundary=caddc028fb5616df9f17ed4decdaa51941b5c6c224115614f03cdab12bec"
          -d "Content-Type: multipart/form-data; boundary=caddc028fb5616df9f17ed4decdaa51941b5c6c224115614f03cdab12bec\r\n\r\n--caddc028fb5616df9f17ed4decdaa51941b5c6c224115614f03cdab12bec\r\nContent-Id:
          field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=2be3c939ee0ae4aef464368bdf7f60b49f8752b5331f7baa3c46574cca8a\r\n\r\n--2be3c939ee0ae4aef464368bdf7f60b49f8752b5331f7baa3c46574cca8a\r\nContent-Id:
          field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=5f623102c3c822ad16f33c227d6bd52f545dfe65efa91936499b5b2e66e3\r\n\r\n--5f623102c3c822ad16f33c227d6bd52f545dfe65efa91936499b5b2e66e3\r\nContent-Id:
          field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data;
          boundary=032ec39623b5cb5e80940c82ea21b966118304093788652971a469945c73\r\n\r\n--032ec39623b5cb5e80940c82ea21b966118304093788652971a469945c73\r\nContent-Id:
          field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false]
          field5.3:example-string field5.4:1.234]]\r\n--032ec39623b5cb5e80940c82ea21b966118304093788652971a469945c73\r\nContent-Id:
          field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--032ec39623b5cb5e80940c82ea21b966118304093788652971a469945c73--\r\n\r\n--5f623102c3c822ad16f33c227d6bd52f545dfe65efa91936499b5b2e66e3\r\nContent-Id:
          field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--5f623102c3c822ad16f33c227d6bd52f545dfe65efa91936499b5b2e66e3--\r\n\r\n--2be3c939ee0ae4aef464368bdf7f60b49f8752b5331f7baa3c46574cca8a\r\nContent-Id:
          field2.2\r\nContent-Type: text/plain\r\n\r\n[2022-01-01T15:00:14Z]\r\n--2be3c939ee0ae4aef464368bdf7f60b49f8752b5331f7baa3c46574cca8a\r\nContent-Id:
          field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--2be3c939ee0ae4aef464368bdf7f60b49f8752b5331f7baa3c46574cca8a--\r\n\r\n--caddc028fb5616df9f17ed4decdaa51941b5c6c224115614f03cdab12bec\r\nContent-Id:
          field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--caddc028fb5616df9f17ed4decdaa51941b5c6c224115614f03cdab12bec--\r\n"'
      - label: PHP
        lang: php
        source: |-
          $url = "https://domain.tld/test-form-data";
          $data = "Content-Type: multipart/form-data; boundary=95045337b4c283f0ffadf919263fe899b75d922f178df9c6cb20f23d8716\r\n\r\n--95045337b4c283f0ffadf919263fe899b75d922f178df9c6cb20f23d8716\r\nContent-Id: field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=b45dcd60a96f2ba750e6a65d026d06b41a1cca97850f6cbbdbedb0c7e87b\r\n\r\n--b45dcd60a96f2ba750e6a65d026d06b41a1cca97850f6cbbdbedb0c7e87b\r\nContent-Id: field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=9a4825418b7ed8a3d87c79fbc4c029c2e4e8259c9d2a8d61bba50ddf69f0\r\n\r\n--9a4825418b7ed8a3d87c79fbc4c029c2e4e8259c9d2a8d61bba50ddf69f0\r\nContent-Id: field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--9a4825418b7ed8a3d87c79fbc4c029c2e4e8259c9d2a8d61bba50ddf69f0\r\nContent-Id: field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=996b69cf44ac57d79cc384007fa5fd17019a8f2ee87dd6f2759e2bbafd46\r\n\r\n--996b69cf44ac57d79cc384007fa5fd17019a8f2ee87dd6f2759e2bbafd46\r\nContent-Id: field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false] field5.3:example-string field5.4:1.234]]\r\n--996b69cf44ac57d79cc384007fa5fd17019a8f2ee87dd6f2759e2bbafd46\r\nContent-Id: field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--996b69cf44ac57d79cc384007fa5fd17019a8f2ee87dd6f2759e2bbafd46--\r\n\r\n--9a4825418b7ed8a3d87c79fbc4c029c2e4e8259c9d2a8d61bba50ddf69f0--\r\n\r\n--b45dcd60a96f2ba750e6a65d026d06b41a1cca97850f6cbbdbedb0c7e87b\r\nContent-Id: field2.2\r\nContent-Type: text/plain\r\n\r\n[2022-01-01T15:00:14Z]\r\n--b45dcd60a96f2ba750e6a65d026d06b41a1cca97850f6cbbdbedb0c7e87b\r\nContent-Id: field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--b45dcd60a96f2ba750e6a65d026d06b41a1cca97850f6cbbdbedb0c7e87b--\r\n\r\n--95045337b4c283f0ffadf919263fe899b75d922f178df9c6cb20f23d8716\r\nContent-Id: field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--95045337b4c283f0ffadf919263fe899b75d922f178df9c6cb20f23d8716--\r\n";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
      - label: JavaScript
        lang: js
        source: |2-

          var url = "https://domain.tld/test-form-data";

          var request = new XMLHttpRequest();
          request.open("POST", url);
          request.setRequestHeader("Content-Type", "multipart/form-data boundary=2a59d43e579bade12c48eb2b00453a86555bf6da7b01cf8bb5813cb5a23d");

          request.send("Content-Type: multipart/form-data; boundary=2a59d43e579bade12c48eb2b00453a86555bf6da7b01cf8bb5813cb5a23d\r\n\r\n--2a59d43e579bade12c48eb2b00453a86555bf6da7b01cf8bb5813cb5a23d\r\nContent-Id: field1.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=7dcfc05b675462f3f485d02f762a3e75ac2eb6d7b5ff25cf3106b1893a01\r\n\r\n--7dcfc05b675462f3f485d02f762a3e75ac2eb6d7b5ff25cf3106b1893a01\r\nContent-Id: field2.2\r\nContent-Type: text/plain\r\n\r\n[2022-01-01T15:00:14Z]\r\n--7dcfc05b675462f3f485d02f762a3e75ac2eb6d7b5ff25cf3106b1893a01\r\nContent-Id: field2.3\r\nContent-Type: text/plain\r\n\r\nexample-string\r\n--7dcfc05b675462f3f485d02f762a3e75ac2eb6d7b5ff25cf3106b1893a01\r\nContent-Id: field2.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=f9cea48065ee3d9d9e49158fa8e701a192575c523e81381cd862dc17e4a6\r\n\r\n--f9cea48065ee3d9d9e49158fa8e701a192575c523e81381cd862dc17e4a6\r\nContent-Id: field3.1\r\nContent-Type: text/plain\r\n\r\nContent-Type: multipart/form-data; boundary=7f8924803ce21985f7295336cd1e45c48daf1fbb54a35559c66cccee7770\r\n\r\n--7f8924803ce21985f7295336cd1e45c48daf1fbb54a35559c66cccee7770\r\nContent-Id: field4.1\r\nContent-Type: text/plain\r\n\r\n[map[field5.1:14 field5.2:[false] field5.3:example-string field5.4:1.234]]\r\n--7f8924803ce21985f7295336cd1e45c48daf1fbb54a35559c66cccee7770\r\nContent-Id: field4.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--7f8924803ce21985f7295336cd1e45c48daf1fbb54a35559c66cccee7770--\r\n\r\n--f9cea48065ee3d9d9e49158fa8e701a192575c523e81381cd862dc17e4a6\r\nContent-Id: field3.2\r\nContent-Type: text/plain\r\n\r\n[example-string]\r\n--f9cea48065ee3d9d9e49158fa8e701a192575c523e81381cd862dc17e4a6--\r\n\r\n--7dcfc05b675462f3f485d02f762a3e75ac2eb6d7b5ff25cf3106b1893a01--\r\n\r\n--2a59d43e579bade12c48eb2b00453a86555bf6da7b01cf8bb5813cb5a23d\r\nContent-Id: field1.2\r\nContent-Type: text/plain\r\n\r\n1234\r\n--2a59d43e579bade12c48eb2b00453a86555bf6da7b01cf8bb5813cb5a23d--\r\n");
          console.log(request.responseText);
  /test-json:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: |
            ok
      x-codeSamples:
      - label: bash/curl
        lang: curl
        source: 'curl https://domain.tld/test-json -X POST -H "Content-Type: application/json
          " -d "{\"field1.1\":{\"field2.1\":{\"field3.1\":{\"field4.1\":[{\"field5.1\":\"14\",\"field5.2\":[false],\"field5.3\":\"example-string\",\"field5.4\":1.234}],\"field4.2\":1234},\"field3.2\":[\"example-string\"]},\"field2.2\":[\"2022-01-01T15:00:14Z\"],\"field2.3\":\"example-string\"},\"field1.2\":1234}"'
      - label: PHP
        lang: php
        source: "$url = \"https://domain.tld/test-json\";\n$data = json_encode(array(\n\t\"field1.1\"
          => array(\n\t\t\"field2.3\" => \"example-string\",\n\t\t\"field2.1\" =>
          array(\n\t\t\t\"field3.1\" => array(\n\t\t\t\t\"field4.1\" => array(\n\t\t\t\t\tarray(\n\t\t\t\t\t\t\"field5.1\"
          => \"14\",\n\t\t\t\t\t\t\"field5.2\" => array(\n\t\t\t\t\t\t\tfalse,\n\t\t\t\t\t\t),\n\t\t\t\t\t\t\"field5.3\"
          => \"example-string\",\n\t\t\t\t\t\t\"field5.4\" => \"1.234\",\n\t\t\t\t\t),\n\t\t\t\t),\n\t\t\t\t\"field4.2\"
          => \"1234\",\n\t\t\t),\n\t\t\t\"field3.2\" => array(\n\t\t\t\t\"example-string\",\n\t\t\t),\n\t\t),\n\t\t\"field2.2\"
          => array(\n\t\t\t\"2022-01-01T15:00:14Z\",\n\t\t),\n\t),\n\t\"field1.2\"
          => \"1234\",\n));\n\n\n$curl = curl_init($url);\ncurl_setopt($curl, CURLOPT_CUSTOMREQUEST,
          \"POST\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER, true);\ncurl_setopt($curl,
          CURLOPT_POSTFIELDS, $data);\nvar_dump(curl_exec($curl)); // Dumps the response\ncurl_close($curl);"
      - label: JavaScript
        lang: js
        source: |2-

          var url = "https://domain.tld/test-json";

          var request = new XMLHttpRequest();
          request.open("POST", url);
          request.setRequestHeader("Content-Type", "application/json");

          request.send("{\"field1.1\":{\"field2.1\":{\"field3.1\":{\"field4.1\":[{\"field5.1\":\"14\",\"field5.2\":[false],\"field5.3\":\"example-string\",\"field5.4\":1.234}],\"field4.2\":1234},\"field3.2\":[\"example-string\"]},\"field2.2\":[\"2022-01-01T15:00:14Z\"],\"field2.3\":\"example-string\"},\"field1.2\":1234}");
          console.log(request.responseText);
  /test-xml:
    post:
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/Level1'
        required: true
      responses:
        "200":
          description: ok
      x-codeSamples:
      - label: bash/curl
        lang: curl
        source: 'curl https://domain.tld/test-xml -X POST -H "Content-Type: text/xml
          " -d "<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-01-01T15:00:14Z</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>"'
      - label: PHP
        lang: php
        source: |-
          $url = "https://domain.tld/test-xml";
          $data = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-01-01T15:00:14Z</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>";

          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
      - label: JavaScript
        lang: js
        source: |2-

          var url = "https://domain.tld/test-xml";

          var request = new XMLHttpRequest();
          request.open("POST", url);
          request.setRequestHeader("Content-Type", "text/xml");

          request.send("<?xml version=\"1.0\" encoding=\"UTF-8\"?><doc><field1.1><field2.1><field3.1><field4.1><field5.1>14</field5.1><field5.2>false</field5.2><field5.3>example-string</field5.3><field5.4>1.234</field5.4></field4.1><field4.2>1234</field4.2></field3.1><field3.2>example-string</field3.2></field2.1><field2.2>2022-01-01T15:00:14Z</field2.2><field2.3>example-string</field2.3></field1.1><field1.2>1234</field1.2></doc>");
          console.log(request.responseText);
