components:
  schemas:
    Data:
      properties:
        field1:
          $ref: "#/components/schemas/Tag1"
        field2:
          $ref: "#/components/schemas/Tag2"
      required:
      - field1
      - field2
      type: object
    Tag:
      oneOf:
      - properties:
          category:
            type: string
        required:
        - category
        type: object
      - $ref: "#/components/schemas/Tag1"
      - $ref: "#/components/schemas/Tag2"
      type: object
    Tag1:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    Tag2:
      properties:
        name:
          type: integer
      required:
      - name
      type: object
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /data:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Data"
        required: true
      responses: null
      x-codeSamples:
      - lang: curl
        source: "curl https://example.tld/data -X POST -H \"Content-Type: application/json \" -d \"{\\\"field1\\\":{\\\"name\\\":\\\"example-string\\\"},\\\"field2\\\":{\\\"name\\\":1234}}\""
        label: bash/curl
      - lang: php
        source: |-
          $url = "https://example.tld/data";
          $data = json_encode(array(
          	"field1" => array(
          		"name" => "example-string",
          	),
          	"field2" => array(
          		"name" => "1234",
          	),
          ));
          
          
          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
        label: PHP
      - lang: js
        source: "\nvar url = \"https://example.tld/data\";\n\nvar request = new XMLHttpRequest();\nrequest.open(\"POST\", url);\nrequest.setRequestHeader(\"Content-Type\", \"application/json\");\n\nrequest.send({\n\t\"field1\": {\n\t\t\"name\": \"example-string\"\n\t},\n\t\"field2\": {\n\t\t\"name\": 1234\n\t}\n});\nconsole.log(request.responseText);"
        label: JavaScript
  /data/{id1}/{id2}:
    parameters:
    - in: path
      name: id1
      required: true
      schema:
        type: string
    - in: path
      name: id2
      required: true
      schema:
        type: integer
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Data"
        required: true
      responses: null
      x-codeSamples:
      - lang: curl
        source: "curl https://example.tld/data/example-string/1234 -X POST -H \"Content-Type: application/json \" -d \"{\\\"field1\\\":{\\\"name\\\":\\\"example-string\\\"},\\\"field2\\\":{\\\"name\\\":1234}}\""
        label: bash/curl
      - lang: php
        source: |-
          $url = "https://example.tld/data/example-string/1234";
          $data = json_encode(array(
          	"field2" => array(
          		"name" => "1234",
          	),
          	"field1" => array(
          		"name" => "example-string",
          	),
          ));
          
          
          $curl = curl_init($url);
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
          curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          var_dump(curl_exec($curl)); // Dumps the response
          curl_close($curl);
        label: PHP
      - lang: js
        source: "\nvar url = \"https://example.tld/data/example-string/1234\";\n\nvar request = new XMLHttpRequest();\nrequest.open(\"POST\", url);\nrequest.setRequestHeader(\"Content-Type\", \"application/json\");\n\nrequest.send({\n\t\"field1\": {\n\t\t\"name\": \"example-string\"\n\t},\n\t\"field2\": {\n\t\t\"name\": 1234\n\t}\n});\nconsole.log(request.responseText);"
        label: JavaScript
servers:
- url: example.tld
