components:
  schemas:
    Data:
      properties:
        field1:
          $ref: '#/components/schemas/Tag1'
        field2:
          $ref: '#/components/schemas/Tag2'
      required:
      - field1
      - field2
      type: object
    Tag:
      oneOf:
      - properties:
          category:
            type: string
        required:
        - category
        type: object
      - $ref: '#/components/schemas/Tag1'
      - $ref: '#/components/schemas/Tag2'
      type: object
    Tag1:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    Tag2:
      properties:
        name:
          type: integer
      required:
      - name
      type: object
info:
  description: A brand new API with no content.  Go nuts!
  title: New API
  version: 1.0.0
openapi: 3.0.2
paths:
  /data:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
        required: true
      responses: null
      x-codeSamples:
      - label: bash/curl
        lang: curl
        source: 'curl https://example.tld/data -X POST -H "Content-Type: application/json
          " -d "{\"field1\":{\"name\":\"example-string\"},\"field2\":{\"name\":1234}}"'
      - label: PHP
        lang: php
        source: "$url = \"https://example.tld/data\";\n$data = json_encode(array(\n\t\"field1\"
          => array(\n\t\t\"name\" => \"example-string\",\n\t),\n\t\"field2\" => array(\n\t\t\"name\"
          => \"1234\",\n\t),\n));\n\n\n$curl = curl_init($url);\ncurl_setopt($curl,
          CURLOPT_CUSTOMREQUEST, \"POST\");\ncurl_setopt($curl, CURLOPT_RETURNTRANSFER,
          true);\ncurl_setopt($curl, CURLOPT_POSTFIELDS, $data);\nvar_dump(curl_exec($curl));
          // Dumps the response\ncurl_close($curl);"
      - label: JavaScript
        lang: js
        source: |2-

          var url = "https://example.tld/data";

          var request = new XMLHttpRequest();
          request.open("POST", url);
          request.setRequestHeader("Content-Type", "application/json");

          request.send("{\"field1\":{\"name\":\"example-string\"},\"field2\":{\"name\":1234}}");
          console.log(request.responseText);
servers:
- url: example.tld
