name: Main
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'

permissions:
  contents: read
  checks: write
  pages: write
  id-token: write

jobs:
  golang_quality:
    uses: CubicrootXYZ/Workflows/.github/workflows/golang_quality.yaml@v0.0.20

  golang_test:
    uses: CubicrootXYZ/Workflows/.github/workflows/golang_test.yaml@v0.0.20