name: Main
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'

jobs: 
  tests:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container: 
      image: golang:1.22
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container: 
      image: golangci/golangci-lint:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Run golangci
        run: golangci-lint run --timeout 3m0s
      